# Generated by Django 5.2.18 on 2026-10-10 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_emisor', models.CharField(max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('mercado', models.CharField(choices=[('ACN', 'Acciones'), ('CFI', 'Cuotas de fondos de inversión'), ('FM', 'Fondos mutuos')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nemotecnico', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('esta_inscrito', models.BooleanField(default=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='calificaciones.emisor')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia_evento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10001)])),
                ('fecha_pago', models.DateField()),
                ('ejercicio_comercial', models.PositiveSmallIntegerField()),
                ('valor_historico', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('is_fut', models.BooleanField(default=False)),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('origen_dato', models.CharField(choices=[('INGRESO_MANUAL', 'Ingreso manual'), ('CARGA_MONTOS', 'Carga por montos'), ('CARGA_FACTORES', 'Carga por factores'), ('BOLSA', 'Bolsa')], default='INGRESO_MANUAL', max_length=20)),
                ('estado_periodo', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_dividendo', models.PositiveIntegerField(default=0)),
                ('tipo_sociedad', models.CharField(blank=True, choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1)),
                ('corredora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='usuarios.corredora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='calificaciones.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='FactorTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(37)])),
                ('monto_financiero', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('factor_calculado', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores', to='calificaciones.calificaciontributaria')),
            ],
            options={
                'ordering': ['columna'],
                'constraints': [models.UniqueConstraint(fields=('calificacion', 'columna'), name='factor_unico_por_columna')],
            },
        ),
    ]
